---
- name: Install hyprland
  become: true
  ansible.builtin.package:
    name: hyprland
    state: present

- name: Install hyprland utilities
  yay:
    name:
      - hypridle-git
      # - hyprlock-git
      - catppuccin-cursors-macchiato
    state: present

# there is a bug in hyprlock that hasn't been fixed in the AUR package yet
# for now, install it from source
- name: Install hyprlock
  ansible.builtin.import_tasks: hyprlock.yaml

- name: Configure hyprland
  ansible.builtin.file:
    src: "{{ (role_path, 'files', 'hypr') | path_join }}"
    dest: "{{ (config_dir, 'hypr') | path_join }}"
    state: link

- name: Enable hypridle systemd service
  ansible.builtin.systemd:
    name: hypridle.service
    enabled: true
    state: started
    scope: user

- name: Reload systemd
  ansible.builtin.systemd:
    name: hyprland.service
    daemon_reload: true
    scope: user
