#!/bin/sh

# Attempt to find an existing ansible installation and if one isn't found install it
if ! ansible_loc="$(type -p ansible-playbook)" || [[ -z $ansible_loc ]]; then
	echo "ansible-playbook not found, attempting to install..."
	if pacman_loc="$(type -p pacman)" && [[ ! -z $pacman_loc ]]; then
		sudo pacman -S ansible
	else
		echo "Unable to automatically install ansible. Unrecognized distribution. Ansible must be installed manually."
		exit 1
	fi
else
	echo "ansible-playbook found at $ansible_loc"
fi

echo "Updating git submodules..."
git submodule update --init --recursive

# even though ansible is supposed to look in this directory by default it
# doesn't seem to be doing that, so setting this is necessary
export ANSIBLE_LIBRARY=library

echo "Bootstrapping local computer..."
ansible-playbook -i hosts --vault-password-file .ansible_vault_pass setup.yml --ask-become-pass $@
