---
# TODO: set default applications: xdg-settings set default-web-browser org.qutebrowser.qutebrowser.desktop
# TODO: Setup audio: Install pipewire, pipewire-audio, pipewire-alsa, pipewire-pulse, wireplumber, qpwgraph, alsa-utils
- name: Setup system
  hosts: localhost
  vars:
    config_dir: "{{ (ansible_user_dir, '.config') | path_join }}"
    source_dir: "{{ (ansible_user_dir, '.local', 'source') | path_join }}"

  pre_tasks:
    - name: Ensure directories exist
      ansible.builtin.file:
        dest: "{{ item }}"
        state: directory
      loop:
        - "{{ config_dir }}"
        - "{{ source_dir }}"

    - name: Load variables
      tags: always
      ansible.builtin.include_vars:
        file: "{{ item }}"
      loop:
        - vars/default.yml
        - vars/{{ ansible_distribution | lower }}.yml

  roles:
    - role: yay
      tags: yay
      when: ansible_distribution == "Archlinux"
    - role: hyprland
      tags: [hyprland, wm]
      when: ansible_distribution == "Archlinux"
    - role: aerospace
      tags: [aerospace, wm]
      when: ansible_distribution == "MacOSX"
    - role: sddm
      tags: sddm
      when: ansible_distribution == "Archlinux"
    - role: swww
      tags: [wallpaper, swww]
      when: ansible_distribution == "Archlinux"
    - role: ags
      tags: [statusbar, ags]
      when: ansible_distribution == "Archlinux"
    - role: sketchybar
      tags: [statusbar, sketchybar]
      when: ansible_distribution == "MacOSX"
    - role: kitty
      tags: kitty
    - role: zsh
      tags: zsh
    - role: tmux
      tags: tmux
    - role: neovim
      tags: neovim
    - role: nvm
      tags: nvm
    - role: asdf
      tags: asdf
    - role: fuzzel
      tags: [launcher, fuzzel]
      when: ansible_distribution == "Archlinux"
    - role: avizo
      tags: avizo
      when: ansible_distribution == "Archlinux"
    - role: spotify
      tags: [apps, spotify]
    - role: asdf
      tags: [utilities, asdf]

  tasks:
    - name: Install packages
      tags: packages
      become: "{{ package_install_requires_elevation }}"
      ansible.builtin.package:
        name: "{{ base_packages | union(dist_packages | default([])) }}"
        state: present

    - name: Install casks
      tags: packages
      community.general.homebrew_cask:
        name: "{{ casks }}"
        state: present
      when: ansible_distribution == "MacOSX"

    - name: Install AUR packages
      tags: packages
      yay:
        name: "{{ aur_packages }}"
        state: present
      when: ansible_distribution == "Archlinux"
