---
- name: Setup system
  hosts: localhost
  vars:
    config_dir: "{{ (ansible_user_dir, '.config') | path_join }}"
    source_dir: "{{ (ansible_user_dir, '.local', 'source') | path_join }}"

  pre_tasks:
    - name: Ensure directories exist
      ansible.builtin.file:
        dest: "{{ item }}"
        state: directory
      loop:
        - "{{ config_dir }}"
        - "{{ source_dir }}"

    - name: Load variables
      tags: always
      ansible.builtin.include_vars:
        file: "{{ item }}"
      loop:
        - vars/default.yml
        - vars/{{ ansible_distribution | lower }}.yml

  roles:
    - role: yay
      tags: yay
      when: ansible_distribution == "Archlinux"
    - role: hyprland
      tags: [hyprland, wm]
      when: ansible_distribution == "Archlinux"
    - role: aerospace
      tags: [aerospace, wm]
      when: ansible_distribution == "MacOSX"
    - role: swww
      tags: [wallpaper, swww]
      when: ansible_distribution == "Archlinux"
    - role: sketchybar
      tags: [statusbar, sketchybar]
      when: ansible_distribution == "MacOSX"
    - role: kitty
      tags: kitty
    - role: zsh
      tags: zsh
    - role: tmux
      tags: tmux
    - role: neovim
      tags: neovim
    - role: nvm
      tags: nvm

  tasks:
    - name: Install packages
      tags: packages
      become: "{{ package_install_requires_elevation }}"
      ansible.builtin.package:
        name: "{{ base_packages | union(dist_packages | default([])) }}"
        state: present

    - name: Install casks
      tags: packages
      community.general.homebrew_cask:
        name: "{{ casks }}"
        state: present
      when: ansible_distribution == "MacOSX"
