---
- name: Setup system
  hosts: localhost

  pre_tasks:
    - name: Setup variables
      ansible.builtin.set_fact:
        config_dir: "{{ (ansible_user_dir, '.config') | path_join }}"
      tags: always

  roles:
    - role: hyprland
      tags: [hyprland, wm]
      when: ansible_distribution == "Archlinux"
    - role: aerospace
      tags: [aerospace, wm]
      when: ansible_distribution == "MacOSX"
    - role: kitty
      tags: kitty
    - role: zsh
      tags: zsh
    - role: tmux
      tags: tmux
    - role: neovim
      tags: neovim
