# https://taskfile.dev

version: "3"

tasks:
  lab-up:
    desc: Bring lab VMs up and online
    cmds:
      - scripts/up.sh

  lab-down:
    desc: Shut down lab VMs
    cmds:
      - scripts/down.sh

  lab-destroy:
    desc: Shut down and remove lab VM and infrastructure
    cmds:
      - scripts/down.sh --destroy
