apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: pihole-admin-sops
    namespace: pihole-system
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:xIouTe9zHKTCk7dtVXpFmrgLdw==,iv:WsD6svE6mm1o/w3/kZnD6Oac67z0+XQT9YMX6BgsKkw=,tag:EXZr4xf6x8X6TqkDaVXCBA==,type:str]
          stringData:
            password: ENC[AES256_GCM,data:M8YGLojzneYkDtO1Q/JkGCl6LABywg/ehQ==,iv:JHG38aq3Wcw5OvkweOYxZal2BqJP35TtZpQiFhICvvQ=,tag:panTBd8WFQAbDcED+hBFIQ==,type:str]
sops:
    age:
        - recipient: age15wkf9vdre5e8meg0pym5sju74wlmgrcsvvgcjedgtvazw7phy3pqzcmd3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFaDA1ajlMS3h6UlQ5NExP
            UlBSWkRGZ0dzLzZtUWpEUWhPbzBFMlVmV0I0ClVsZkRpeXJZMjFwOU5oN0pndC9x
            aThhN3BXU25CeGNsTEthT29Edyt1UGcKLS0tIEtRS1pwZXpFNW0yVTFNdi80QlE2
            SGswbjNHS2pLUVlnMWVxMURxQXNPYzgKewOgjqtdpgXAxT7ZMQnWnpgjaCMBtlTH
            5EiljimO4yaeZzuMgn01vPUanW4zFNEQ8s2wVS9nbXgNQIdukJpRbA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yw8vgjhe4jnktydagv9z5hpr54aa3kt04v5h9aau797tx0t2z4uql92jsu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLRCtIUzRBN09uNnNLVGFt
            ejRzYXVsZGZZMXgzVjdxNnBrK3AxRHNNcFM0CnhTMWRZa0E3emF6ZDk0YUFZVld2
            WXJMM2p5T3RpRXNHbWY0SityOCtpMGMKLS0tIFlxUHRzWERacGpsSUNSRHRNS3pQ
            UGRwaU81ZS8rc3JBVmV5MkpwVkQ0TmcKbloKb0l7OAhRO9Yr1PczYAY0i4nTJUDJ
            8BvwNOuwT5OW6Gq2o60QfN++KNUmczGb8jXSJidahqjzsd6HU/BXIA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ayu2ja9u95gnezp32vr26tj28xnee9mjazydp8mafdj8fhsntekqrfwcp0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzeElTUytjQTZzU1B3TFBV
            ZlpCd0MvaXVueFFTcWFBcitvRGhBYU9kMVNrCndLOUlNdjdwTlJBK3JML3AzYlRV
            cHlRTnhra0ZsYzF0alRCMGU1TmtmMTQKLS0tIHpEQVFLMVFlNzZNcnBpQUZKRFpJ
            TUtMWVROYmY3eUpBVVE4VlVCOU5Vc1UKX5IQynaTOEnnPpq+ysdu2BtyG/eZKRmj
            35zQAC6q6CZD4P0x2UdlK2FQNGyy5BpzhmxZWG15WhZgPHNr2Hj2GQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-28T00:48:16Z"
    mac: ENC[AES256_GCM,data:ZW3o0xVJQFeFidDWzDR+ZJS1V7Du0HS1Z+sICxp8x1dDLfRnB8ZZhOSJxUhi3WBhTs4l4ZsROR3GpuaRexPQ1at6syldDUBftMUbuNtMCxSa+lozeC2btqCi8NHfkHVcvCfkvgsjAeq0i9ckMG2fUpA3xIOBjvIHAEH5f/ebACY=,iv:+MYQQoeN5Koy1LH7wzu30o+miRH7N5a+hoeZUC+Dfoo=,tag:aqtZo5KzboStnpNTwoGWZQ==,type:str]
    encrypted_suffix: Templates
    version: 3.11.0
