---
- name: Install dependencies
  ansible.builtin.package:
    name: [curl, git]
    state: present

- name: Checkout asdf
  ansible.builtin.git:
    repo: https://github.com/asdf-vm/asdf.git
    dest: "{{ (ansible_user_dir, '.asdf') | path_join }}"
    version: v0.14.0
