---
- name: Link .zshrc
  ansible.builtin.file:
    src: "{{ (role_path, 'files', 'zshrc') | path_join }}"
    dest: "{{ (ansible_user_dir, '.zshrc') | path_join }}"
    state: link

- name: Install oh-my-posh (yay)
  yay:
    name: oh-my-posh
    state: present
  when: ansible_distribution == "Archlinux"

- name: Install oh-my-posh (homebrew)
  community.general.homebrew_cask:
    name: oh-my-posh
    state: present
  when: ansible_distribution == "MacOSX"
