---
# default variables
package_install_requires_elevation: true
base_packages:
  - bat
  - curl
  - eza
  - fzf
  - jq
  - lazygit
  - ripgrep
  - tree
  - zoxide

neovim_force_build: false
neovim_version: nightly
neovim_build_type: Release

asdf_plugins: []
