# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  ascii-nvim = {
    pname = "ascii-nvim";
    version = "70783fea66e99525221e52dce3b3489c05354181";
    src = fetchFromGitHub {
      owner = "MaximilianLloyd";
      repo = "ascii.nvim";
      rev = "70783fea66e99525221e52dce3b3489c05354181";
      fetchSubmodules = false;
      sha256 = "sha256-2CE03Lvyn7Ta8yd5pR6ZXGiXAyYtVxYPynUmhHATqG8=";
    };
    date = "2025-10-20";
  };
  gopher-nvim = {
    pname = "gopher-nvim";
    version = "v0.5.0";
    src = fetchFromGitHub {
      owner = "olexsmir";
      repo = "gopher.nvim";
      rev = "v0.5.0";
      fetchSubmodules = false;
      sha256 = "sha256-iXTmgdADtZFQVm+IN+JoPActGuO8r7VTeHKJdkEgmVo=";
    };
  };
  neotest-fix = {
    pname = "neotest-fix";
    version = "ce51b2834f6f4e9d9a09c1047a0d1f627b13161a";
    src = fetchFromGitHub {
      owner = "archie-judd";
      repo = "neotest";
      rev = "ce51b2834f6f4e9d9a09c1047a0d1f627b13161a";
      fetchSubmodules = false;
      sha256 = "sha256-EpkobU9KzMpvQr+XZKy9abna1q/TZSKr469ggx+tvgk=";
    };
  };
  neotest-golang-fix = {
    pname = "neotest-golang-fix";
    version = "v2.7.2";
    src = fetchFromGitHub {
      owner = "fredrikaverpil";
      repo = "neotest-golang";
      rev = "v2.7.2";
      fetchSubmodules = false;
      sha256 = "sha256-oZWb6GsZTgclKFyDgZWWANmfPRjg0LZgFymQs2SC8Rc=";
    };
  };
  reactive-nvim = {
    pname = "reactive-nvim";
    version = "v1.2.1";
    src = fetchFromGitHub {
      owner = "rasulomaroff";
      repo = "reactive.nvim";
      rev = "v1.2.1";
      fetchSubmodules = false;
      sha256 = "sha256-LZCCboM/fw+Kw6wVskrPs6nr4SFLoD0pi6EMxSIGelw=";
    };
  };
}
