---
- name: Install sketchybar
  community.general.homebrew:
    name: sketchybar
    state: present

- name: Configure sketchybar
  ansible.builtin.file:
    src: "{{ (role_path, 'files', 'sketchybar') | path_join }}"
    dest: "{{ (config_dir, 'sketchybar') | path_join }}"
    state: link

- name: Start sketchybar
  homebrew_services:
    name: sketchybar
    state: started
