- name: Link wallpapers directory
  ansible.builtin.file:
    state: link
    src: "{{ (playbook_dir, '../wallpapers') | path_join }}"
    dest: "{{ (ansible_env.HOME, 'wallpapers') | path_join }}"

- name: Link systemd units for wallpapers
  ansible.builtin.file:
    state: link
    src: "{{ (src_files_dir, item) | path_join }}"
    dest: "{{ (dotconfig_dir, 'systemd', 'user', item) | path_join }}"
  loop: [swww.service, wallpaper-random.service, wallpaper-random.timer]

- name: Start wallpaper services
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    daemon_reload: true
    enabled: true
    scope: user
  loop: [swww.service, wallpaper-random.timer]
