---
- name: Setup vars
  ansible.builtin.set_fact:
    neovim_source_dir: "{{ (source_dir, 'neovim') | path_join }}"

- name: Install build prerequisites
  ansible.builtin.package:
    name: "{{ pkgs[ansible_distribution] }}"
    state: present
  vars:
    pkgs:
      Archlinux: [base-devel, cmake, unzip, ninja, curl]

- name: Clone neovim repo
  ansible.builtin.git:
    repo: https://github.com/neovim/neovim
    dest: "{{ neovim_source_dir }}"
    version: "{{ neovim_version | default('stable') }}"
    depth: 1
    single_branch: true
  register: nvim_clone

- name: Clean build directory
  community.general.make:
    chdir: "{{ neovim_source_dir }}"
    target: distclean
  when: nvim_clone.changed or neovim_force_build

- name: Build neovim
  community.general.make:
    chdir: "{{ neovim_source_dir }}"
    params:
      CMAKE_BUILD_TYPE: "{{ neovim_build_type | default('Release') }}"
  when: nvim_clone.changed or neovim_force_build

- name: Install neovim
  become: true
  community.general.make:
    chdir: "{{ neovim_source_dir }}"
    target: install
  when: nvim_clone.changed or neovim_force_build

# - name: Install neovim
#   become: "{{ ansible_distribution != 'MacOSX' }}"
#   ansible.builtin.package:
#     name: neovim
#     state: present

- name: Configure neovim
  ansible.builtin.file:
    src: "{{ (role_path, 'files', 'nvim') | path_join }}"
    dest: "{{ (config_dir, 'nvim') | path_join }}"
    state: link
